export const DEFAULT_VALUE = '  '
export const INITIAL_STATE = [
  [DEFAULT_VALUE, DEFAULT_VALUE, DEFAULT_VALUE],
  [DEFAULT_VALUE, DEFAULT_VALUE, DEFAULT_VALUE],
  [DEFAULT_VALUE, DEFAULT_VALUE, DEFAULT_VALUE]
]

